### ISSUE TITLE
MultinomialNB vs GaussianNB

### ISSUE THREAD

**Issue by koaning** [palewire/storysniffer#12]
I had a quick look at the notebook and I noticed that you set the output of the CountVectorizer to be dense. Your document suggests that this is because `GaussianNB` demands it, which is true, but it makes me wonder why you didn't choose to use [MultinomialNB](https://scikit-learn.org/stable/modules/naive_bayes.html#multinomial-naive-bayes) (this variant allows for sparse input). I'm curious, is there a reason why you prefer to use `GaussianNB` here?

**Comment by palewire** [comment]
I don't have a strong preference one way or the other, I just want a good result. If the Multinomial will work better, or require less code, I am open to the switch. You want to test it out?

**Comment by koaning** [comment]
I would love to!

... but I'm going on parental leave tomorrow, so it may take a while before I can pick this up. 😅

**Comment by palewire** [comment]
Okay. I'll close the ticket for now. If you want to submit a pull request later that's great.
